name: 'medicare_cclf_connector'
version: '0.1.2'
config-version: 2

profile: default

vars:

  ## Set the database and schema where raw CCLF data is stored
  input_database: tuva
  input_schema: raw_data

  claims_enabled: true

  ## Uncomment this variable if enrollment source is member months
#  member_months_enrollment: true

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
   medicare_cclf_connector:
     final:
       +materialized: table
     intermediate:
       +materialized: table
     staging:
       +materialized: view
